### ISSUE TITLE
POC  Create tasks from curriculum description

### ISSUE THREAD

**Issue by nesterone** [Mentorioum/mentoriumbot#32]
- mentor create a task with link and mention trainee to work with 
- the bot should prep tasks and assign one task for trainee and one for a mentor to verify 
- the bot should close the main task when both participants done

**Comment by 0pdd** [comment]
@nesterone the puzzle [#39](https://github.com/Mentorioum/mentoriumbot/issues/39) is still not solved.

**Comment by walle010101** [comment]
Hi there ! 0pdd

**Comment by 0pdd** [comment]
@nesterone 2 puzzles [#41](https://github.com/Mentorioum/mentoriumbot/issues/41), [#42](https://github.com/Mentorioum/mentoriumbot/issues/42) are still not solved; solved: [#39](https://github.com/Mentorioum/mentoriumbot/issues/39).

**Comment by walle010101** [comment]
Hi there ! 0pdd

**Comment by nesterone** [comment]
> mentor create a task with link and mention trainee to work with
the bot should prep tasks and assign one task for trainee and one for a mentor to verify

done

> the bot should close the main task when both participants done

not done yet

**Comment by 0pdd** [comment]
@nesterone 6 puzzles [#46](https://github.com/Mentorioum/mentoriumbot/issues/46), [#47](https://github.com/Mentorioum/mentoriumbot/issues/47), [#48](https://github.com/Mentorioum/mentoriumbot/issues/48), [#49](https://github.com/Mentorioum/mentoriumbot/issues/49), [#50](https://github.com/Mentorioum/mentoriumbot/issues/50), [#51](https://github.com/Mentorioum/mentoriumbot/issues/51) are still not solved; solved: [#39](https://github.com/Mentorioum/mentoriumbot/issues/39), [#41](https://github.com/Mentorioum/mentoriumbot/issues/41), [#42](https://github.com/Mentorioum/mentoriumbot/issues/42).

**Comment by walle010101** [comment]
Hi there ! 0pdd

**Comment by 0pdd** [comment]
@nesterone 6 puzzles [#46](https://github.com/Mentorioum/mentoriumbot/issues/46), [#47](https://github.com/Mentorioum/mentoriumbot/issues/47), [#48](https://github.com/Mentorioum/mentoriumbot/issues/48), [#50](https://github.com/Mentorioum/mentoriumbot/issues/50), [#51](https://github.com/Mentorioum/mentoriumbot/issues/51), [#52](https://github.com/Mentorioum/mentoriumbot/issues/52) are still not solved; solved: [#39](https://github.com/Mentorioum/mentoriumbot/issues/39), [#41](https://github.com/Mentorioum/mentoriumbot/issues/41), [#42](https://github.com/Mentorioum/mentoriumbot/issues/42), [#49](https://github.com/Mentorioum/mentoriumbot/issues/49).

**Comment by walle010101** [comment]
Hi there ! 0pdd

**Comment by nesterone** [comment]
https://github.com/bpmn-io/bpmn-moddle/
