### ISSUE TITLE
notification.service.ts:75: - Integrate with markdown parser

### ISSUE THREAD

**Issue by 0pdd** [Mentorioum/mentoriumbot#42]
The puzzle `39-e168d129` from #39 has to be resolved: 

https://github.com/Mentorioum/mentoriumbot/blob/550fef15efcdc6cabcb3cbb72183d7d084ee30a9/src/notification.service.ts#L75-L75

The puzzle was created by nesterone on 23-Mar-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by walle010101** [comment]
Hi there ! 0pdd

**Comment by nesterone** [comment]
done

**Comment by 0pdd** [comment]
@0pdd 5 puzzles [#47](https://github.com/Mentorioum/mentoriumbot/issues/47), [#48](https://github.com/Mentorioum/mentoriumbot/issues/48), [#49](https://github.com/Mentorioum/mentoriumbot/issues/49), [#50](https://github.com/Mentorioum/mentoriumbot/issues/50), [#51](https://github.com/Mentorioum/mentoriumbot/issues/51) are still not solved.

**Comment by walle010101** [comment]
Hi there ! 0pdd

**Comment by 0pdd** [comment]
@0pdd 5 puzzles [#47](https://github.com/Mentorioum/mentoriumbot/issues/47), [#48](https://github.com/Mentorioum/mentoriumbot/issues/48), [#50](https://github.com/Mentorioum/mentoriumbot/issues/50), [#51](https://github.com/Mentorioum/mentoriumbot/issues/51), [#52](https://github.com/Mentorioum/mentoriumbot/issues/52) are still not solved; solved: [#49](https://github.com/Mentorioum/mentoriumbot/issues/49).

**Comment by walle010101** [comment]
Hi there ! 0pdd

**Comment by 0pdd** [comment]
@0pdd 5 puzzles [#unknown](), [#unknown](), [#unknown](), [#unknown](), [#unknown]() are still not solved.
